### ISSUE TITLE
Error- FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by shikhadabas** [corda/corda-settler#16]
I tried to run corda Settler as per instruction given. I tried below mentioned command:-

cd corda-settler
./gradlew clean deployNodes

While executing the command I got below mentioned error:-
Bootstrapping local test network in /home/niit/Corda-Workspace/corda-settler/build/nodes
FAILURE: Build failed with an exception. 
What went wrong:Execution failed for task ':deployCustomNodes'.
No nodes found 

This command created the empty nodes folder in build/nodes of all 4 nodes:- Notary, Oracle , PartyA , PartyB.
Next step we tried is : Now we have tried to create the Nodes with the help of network bootstraper jar file by using the below command, I have copied all the four nodes configuration file in the nodesonfiguration directory and it has created the structure of all the nodes.
java -jar corda-tools-network-bootstrapper-4.1-RC01.jar --dir nodesonfiguration

After that we have created  the jar file for the cordapps with eclipse - dependencies mentioned in build.gradle.

Then I have copied all the below mentioned jar  in the respective nodes cordapp 
•	corda-finance-5.0-SNAPSHOT.jar
•	cordapp.jar
•	cordapp-contracts-states.jar
•	corda-settler.jar
•	oracle.jar
•	ripple.jar

My current corda platform version is 5.0
Then I tried to run the ./runnodes from build/nodes folder, now I am getting the below error.

Logs can be found in : /home/Corda-Workspace/corda-settler/build/nodes/Notary/logs
Exception in thread "main" java.util.ServiceConfigurationError: net.corda.core.serialization.SerializationWhitelist: Provider com.r3.corda.finance.obligation.SerializationWhitelist not found
at java.util.ServiceLoader.fail(ServiceLoader.java:239)
at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1062)
at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1095)
at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1086)
at net.corda.node.internal.cordapp.JarScanningCordappLoader.findPlugins(JarScanningCordappLoader.kt:263)
at net.corda.node.internal.cordapp.JarScanningCordappLoader.toCordapp(JarScanningCordappLoader.kt:145)
at net.corda.node.internal.cordapp.JarScanningCordappLoader.loadCordapps(JarScanningCordappLoader.kt:104)
at net.corda.node.internal.cordapp.JarScanningCordappLoader.access$loadCordapps(JarScanningCordappLoader.kt:42)
at net.corda.node.internal.cordapp.JarScanningCordappLoader$cordapps$2.invoke(JarScanningCordappLoader.kt:54)
at net.corda.node.internal.cordapp.JarScanningCordappLoader$cordapps$2.invoke(JarScanningCordappLoader.kt:42)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at net.corda.node.internal.cordapp.JarScanningCordappLoader.getCordapps(JarScanningCordappLoader.kt)
at net.corda.node.internal.cordapp.CordappLoaderTemplate$cordappSchemas$2.invoke(JarScanningCordappLoader.kt:381)
at net.corda.node.internal.cordapp.CordappLoaderTemplate$cordappSchemas$2.invoke(JarScanningCordappLoader.kt:367)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at net.corda.node.internal.cordapp.CordappLoaderTemplate.getCordappSchemas(JarScanningCordappLoader.kt)
at net.corda.node.internal.AbstractNode.<init>(AbstractNode.kt:152)
at net.corda.node.internal.AbstractNode.<init>(AbstractNode.kt:125)
at net.corda.node.internal.Node.<init>(Node.kt:97)
at net.corda.node.internal.Node.<init>(Node.kt:96)
at net.corda.node.internal.NodeStartup.createNode(NodeStartup.kt:169)
at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:161)
at net.corda.node.internal.NodeStartup$initialiseAndRun$5.invoke(NodeStartup.kt:116)
at net.corda.node.internal.NodeStartupLogging$DefaultImpls.attempt(NodeStartup.kt:445)
at net.corda.node.internal.NodeStartup.attempt(NodeStartup.kt:116)
at net.corda.node.internal.NodeStartup.initialiseAndRun(NodeStartup.kt:1

Please suggest where I am wrong or what needs to be done

**Comment by roger3cev** [comment]
Will look into it. Cheers

**Comment by roger3cev** [comment]
I fixed it, it was due to an incompatible version of the corda gradle plugins with the current used version of corda.

**Comment by joeldudleyr3** [comment]
@roger3cev What was the Corda version and Gradle plugins version being used?

**Comment by roger3cev** [comment]
@joeldudley `5.0-SNAPSHOT` and gradle plugins `3.2.1`
